lane :android_debug_file do
  proguard(
    flavor: 'full',
    extra_files: [
      'app/src/main/AndroidManifest.xml'
    ]
  )
end

lane :ios_debug_file do
  dsym(
    scheme: 'AppName',
    overwrite: true
  )
end

lane :list_ios_dsym do
  # list all dSYMs
  list_dsym

  # Filter by scheme name
  list_dsym(scheme: 'AppName')
end
